# Stage 1: Build
FROM node:22-alpine AS builder

WORKDIR /app

# Copy package.json + lockfile (better cache)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build NestJS project
RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]
